
  name: silent_speech
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch=2.0
  - torchvision
  - torchaudio
  - numpy
  - matplotlib
  - scipy
  - tqdm
  - pip
  - pip:
    - streamlit
    - pandas
    - soundfile
    - absl-py
